name       : qt6-tools
version    : 6.2.1
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qttools-everywhere-src-6.2.1.tar.xz : 5a856d3d3d5fe6e15dc3f1af707a0ef1df2e687850403fc94af635edb9312bfb
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 QtTools Module
description: |
    Qt is a set of libraries for developing applications.  This package contains base tools, like string, xml, and network handling.
clang      : yes
builddeps  :
    - pkgconfig(Qt6Qml)
rundeps    :
    - devel :
        - qt6-declarative-devel
setup      : |
    %cmake_ninja \
        -DCMAKE_C_COMPILER=$CC \
        -DCMAKE_CXX_COMPILER=$CXX \
        -DINSTALL_PUBLICBINDIR=usr/bin
build      : |
    %ninja_build
install    : |
    %ninja_install

    pushd $installdir
    install -dm00755 usr/bin
    while read _line; do
        ln -s $_line
    done < %workdir%/solusBuildDir/user_facing_tool_links.txt
    popd

    install -Dm00644 src/assistant/assistant/images/assistant.png $installdir/usr/share/icons/hicolor/32x32/apps/assistant6.png
    install -Dm00644 src/assistant/assistant/images/assistant-128.png $installdir/usr/share/icons/hicolor/128x128/apps/assistant6.png
    install -Dm00644 src/linguist/linguist/images/icons/linguist-32-32.png $installdir/usr/share/icons/hicolor/128x128/apps/linguist6.png
    install -Dm00644 src/linguist/linguist/images/icons/linguist-128-32.png $installdir/usr/share/icons/hicolor/128x128/apps/linguist6.png
    install -Dm00644 src/designer/src/designer/images/designer.png $installdir/usr/share/icons/hicolor/128x128/apps/designer6.png
    install -Dm00644 src/qdbus/qdbusviewer/images/qdbusviewer.png $installdir/usr/share/icons/hicolor/32x32/apps/qdbusviewer6.png
    install -Dm00644 src/qdbus/qdbusviewer/images/qdbusviewer-128.png $installdir/usr/share/icons/hicolor/128x128/apps/qdbusviewer6.png
    install -Dm00644 $pkgfiles/designer6.desktop $installdir/usr/share/applications/designer6.desktop
    install -Dm00644 $pkgfiles/linguist6.desktop $installdir/usr/share/applications/linguist6.desktop
    install -Dm00644 $pkgfiles/assistant6.desktop $installdir/usr/share/applications/assistant6.desktop
    install -Dm00644 $pkgfiles/qdbusviewer6.desktop $installdir/usr/share/applications/qdbusviewer6.desktop
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt6/bin
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
    - main :
        - /usr/bin/qdbus6
        - /usr/lib64/qt6/bin/qdbus
    - ^designer6 :
        - /usr/bin/designer6
        - /usr/lib64/qt6/bin/designer
        - /usr/lib64/libQt6Designer*
        - /usr/share/applications/designer6.desktop
        - /usr/lib64/qt6/plugins/designer/libqquickwidget.so
        - /usr/share/icons/hicolor/128x128/apps/designer6.png
    - ^qdbusviewer6 :
        - /usr/bin/qdbusviewer6
        - /usr/lib64/qt6/bin/qdbusviewer
        - /usr/share/applications/qdbusviewer6.desktop
        - /usr/share/icons/hicolor/128x128/apps/qdbusviewer6.png
        - /usr/share/icons/hicolor/32x32/apps/qdbusviewer6.png
